project_name: minitunnel
builds:
  - id: minitunnel
    main: ./cmd/mt
    binary: mt
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    flags:
      - -v
      - -trimpath
    ldflags:
      - -s -w
archives:
  - files:
      - none*
    format_overrides:
      - goos: windows
        format: zip
